defmodule BexioApiClient.Contacts.Contact do
  @type t :: %__MODULE__{
          id: integer(),
          nr: String.t(),
          contact_type: atom(),
          name_1: String.t(),
          name_2: String.t(),
          salutation_id: integer(),
          salutation_form: integer(),
          title_id: integer(),
          birthday: Date.t(),
          address: String.t(),
          postcode: String.t(),
          city: String.t(),
          country_id: integer(),
          mail: String.t(),
          mail_second: String.t(),
          phone_fixed: String.t(),
          phone_fixed_second: String.t(),
          phone_mobile: String.t(),
          fax: String.t(),
          url: String.t(),
          skype_name: String.t(),
          remarks: String.t(),
          language_id: integer(),
          contact_group_ids: [integer()],
          contact_branch_ids: [integer()],
          user_id: integer(),
          owner_id: integer(),
          updated_at: DateTime.t()
        }
  @enforce_keys [
    :nr,
    :contact_type,
    :name_1,
    :contact_group_ids,
    :contact_branch_ids,
    :user_id,
    :owner_id,
    :updated_at
  ]
  defstruct [
    :id,
    :nr,
    :contact_type,
    :name_1,
    :name_2,
    :salutation_id,
    :salutation_form,
    :title_id,
    :birthday,
    :address,
    :postcode,
    :city,
    :country_id,
    :mail,
    :mail_second,
    :phone_fixed,
    :phone_fixed_second,
    :phone_mobile,
    :fax,
    :url,
    :skype_name,
    :remarks,
    :language_id,
    :contact_group_ids,
    :contact_branch_ids,
    :user_id,
    :owner_id,
    :updated_at
  ]
end
